<a href="https://colab.research.google.com/github/idrissdeme/Aulas-Python-IRD/blob/main/renomeando_colunas_de_Programa_calculo_Calibracao_LN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from math import *
import xlrd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
table0 = pd.read_excel('/content/drive/MyDrive/Planilha de calculo de valicao (2).xlsx',sheet_name='Dados_python')
#Vamos criar uma nova dataFrame para evitar mexer nos no dataframe originlamente importados
display(table0) 

table = table0   # criação de uma nova daframe com o nome "tabela" onde os nome das colunas seraão alterada para fim dos cálculos. Assim temos dois dataFrame
# O dataFrame original continua com os mesmos títulos e o dataframe novo tem os nomes de colunas alterados para os cálculos

# renomamos as colunas agora no nosso novo data frame
table.rename(columns = {'q0':'q0', 'Cont. Decaimento (H)':'Lambida_h', 'Cont. Decaimento (s)':'Lambida_s', 'h*f (10)\npSv.cm2':'h_10', 'hpf (10; a)\npSv.cm2':'hp', 'Coeficiente de atenuação \nlinear (cm-1)':'Sec_choque', 'A':'A','Espalhamento':'E' }, inplace = True)
#q0=8;Lambida_h=11; Lambida_s=12; h_10=14; hp=15; Sec_choque=17; A=18; E=19;
display(table)

,Número série,Modelo,Atividade \nnominal,Espectro,Taxa de emissão\nCertificado de Calibração,Incerteza\n(K=1),Data de Calibração,Data referencia \nCertificado calibração,q0,Anos : \nData Referência - \nData Calibração,Meia Vida,Cont. Decaimento (H),Cont. Decaimento (s),uλ,h*f (10)\npSv.cm2,hpf (10; a)\npSv.cm2,uh (%),Coeficiente de atenuação \nlinear (cm-1),A,Espalhamento
0,66,SN3,1 Ci,Am241/Be9,2217000,0.006500,1994-06-22 00:00:00,1994-06-22 00:00:00,2.117824e+06,28.536530,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
1,17 1408,"19.2/11,2",1 Ci,Am241/Be9,2306000,0.010624,2021-10-08 00:00:00,2021-10-08 00:00:00,2.301420e+06,1.239574,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
2,80,SN4,5 Ci,Am241/Be9,10720000,0.007500,2007-05-10 00:00:00,2007-05-10 00:00:00,1.045421e+07,15.654666,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
3,81,SN4,5 Ci,Am241/Be9,11080000,0.007500,2004-07-07 00:00:00,2004-07-07 00:00:00,1.075619e+07,18.493878,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
4,A597,31/105,16 Ci,Am241/Be9,38760000,0.010578,2017-03-14 00:00:00,2021-04-01 00:00:00,3.865076e+07,1.759777,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
5,A397,31/105,16 Ci,Am241/Be9,39650000,0.011097,2022-08-19 00:00:00,2022-08-19 00:00:00,3.962603e+07,0.377133,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
6,A639,31/105,16 Ci,Am241/Be9,37800000,0.010582,2017-03-14 00:00:00,2021-04-01 00:00:00,3.769347e+07,1.759777,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
7,A441,31/105,16 Ci,Am241/Be9,39350000,0.011055,2022-08-19 00:00:00,2022-08-19 00:00:00,3.932621e+07,0.377133,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
8,A1505,31/105,16 Ci,Am241/Be9,39140000,0.011269,2021-10-07 00:00:00,2021-10-07 00:00:00,3.906210e+07,1.242312,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
9,FTC CF 3567,"10 S (120,7 ug)","120,7 ug",Cf252,280000000,0.007500,2009-02-03 00:00:00,2009-02-03 00:00:00,7.320667e+06,13.916094,2.647,2.987240e-05,8.297888e-09,0.000964,385.000000,400.0000,0.01,0.000106,1,1
10,FTC CF 3567,"10 S (120,7 ug)","120,7 ug",Cf252 + D2O,280000000,0.007500,2009-02-03 00:00:00,2009-02-03 00:00:00,7.320667e+06,13.916094,2.647,2.987240e-05,8.297888e-09,0.000964,105.000000,110.0000,0.04,0.000296,1,1
11,A639/A441/A397/A597,0,0,"Fluxo térmico (0 a 0,4eV)",155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529261e+08,10.006360,432.200,1.829529e-07,5.082024e-11,0.001379,19.050000,19.8000,0.04,0.000000,1,1
12,A639/A441/A397/A597,0,0,"Fluxo térmico (0,4 a 12 MeV)",155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529317e+08,10.006360,433.200,1.825305e-07,5.070293e-11,0.001379,132.566667,126.7330,0.04,0.000000,1,1
13,A639/A441/A397/A597,0,0,Fluxo térmico (0 a 12 MeV),155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529374e+08,10.006360,434.200,1.821102e-07,5.058616e-11,0.001379,31.300000,30.1333,0.04,0.000000,1,1
14,Pu-238Be-9,0,0,0,0,0.000000,00:00:00,00:00:00,0.000000e+00,0.000000,0.000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0000,0.00,0.000000,1,1

,Número série,Modelo,Atividade \nnominal,Espectro,Taxa de emissão\nCertificado de Calibração,Incerteza\n(K=1),Data de Calibração,Data referencia \nCertificado calibração,q0,Anos : \nData Referência - \nData Calibração,Meia Vida,Lambida_h,Lambida_s,uλ,h_10,hp,uh (%),Sec_choque,A,E
0,66,SN3,1 Ci,Am241/Be9,2217000,0.006500,1994-06-22 00:00:00,1994-06-22 00:00:00,2.117824e+06,28.536530,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
1,17 1408,"19.2/11,2",1 Ci,Am241/Be9,2306000,0.010624,2021-10-08 00:00:00,2021-10-08 00:00:00,2.301420e+06,1.239574,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
2,80,SN4,5 Ci,Am241/Be9,10720000,0.007500,2007-05-10 00:00:00,2007-05-10 00:00:00,1.045421e+07,15.654666,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
3,81,SN4,5 Ci,Am241/Be9,11080000,0.007500,2004-07-07 00:00:00,2004-07-07 00:00:00,1.075619e+07,18.493878,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
4,A597,31/105,16 Ci,Am241/Be9,38760000,0.010578,2017-03-14 00:00:00,2021-04-01 00:00:00,3.865076e+07,1.759777,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
5,A397,31/105,16 Ci,Am241/Be9,39650000,0.011097,2022-08-19 00:00:00,2022-08-19 00:00:00,3.962603e+07,0.377133,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
6,A639,31/105,16 Ci,Am241/Be9,37800000,0.010582,2017-03-14 00:00:00,2021-04-01 00:00:00,3.769347e+07,1.759777,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
7,A441,31/105,16 Ci,Am241/Be9,39350000,0.011055,2022-08-19 00:00:00,2022-08-19 00:00:00,3.932621e+07,0.377133,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
8,A1505,31/105,16 Ci,Am241/Be9,39140000,0.011269,2021-10-07 00:00:00,2021-10-07 00:00:00,3.906210e+07,1.242312,432.200,1.829529e-07,5.082024e-11,0.001379,391.000000,411.0000,0.04,0.000089,1,1
9,FTC CF 3567,"10 S (120,7 ug)","120,7 ug",Cf252,280000000,0.007500,2009-02-03 00:00:00,2009-02-03 00:00:00,7.320667e+06,13.916094,2.647,2.987240e-05,8.297888e-09,0.000964,385.000000,400.0000,0.01,0.000106,1,1
10,FTC CF 3567,"10 S (120,7 ug)","120,7 ug",Cf252 + D2O,280000000,0.007500,2009-02-03 00:00:00,2009-02-03 00:00:00,7.320667e+06,13.916094,2.647,2.987240e-05,8.297888e-09,0.000964,105.000000,110.0000,0.04,0.000296,1,1
11,A639/A441/A397/A597,0,0,"Fluxo térmico (0 a 0,4eV)",155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529261e+08,10.006360,432.200,1.829529e-07,5.082024e-11,0.001379,19.050000,19.8000,0.04,0.000000,1,1
12,A639/A441/A397/A597,0,0,"Fluxo térmico (0,4 a 12 MeV)",155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529317e+08,10.006360,433.200,1.825305e-07,5.070293e-11,0.001379,132.566667,126.7330,0.04,0.000000,1,1
13,A639/A441/A397/A597,0,0,Fluxo térmico (0 a 12 MeV),155400000,0.015000,2013-01-01 00:00:00,2013-01-01 00:00:00,1.529374e+08,10.006360,434.200,1.821102e-07,5.058616e-11,0.001379,31.300000,30.1333,0.04,0.000000,1,1
14,Pu-238Be-9,0,0,0,0,0.000000,00:00:00,00:00:00,0.000000e+00,0.000000,0.000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0000,0.00,0.000000,1,1

In [ ]:
fonte=0
for fonte in [0,1,2,3,4,5,6,7,8,9,10,11,12,13]:
  print(fonte, '.','modelo da fonte =',table.iloc[fonte,1], table.iloc[fonte,0])
fonte = int(input("Índice da Fonte: "))
print(fonte)

0 . modelo da fonte = SN3 66
1 . modelo da fonte = 19.2/11,2 17 1408
2 . modelo da fonte = SN4 80
3 . modelo da fonte = SN4 81
4 . modelo da fonte = 31/105 A597
5 . modelo da fonte = 31/105 A397
6 . modelo da fonte = 31/105 A639
7 . modelo da fonte = 31/105 A441
8 . modelo da fonte = 31/105 A1505
9 . modelo da fonte = 10 S (120,7 ug) FTC CF 3567
10 . modelo da fonte = 10 S (120,7 ug) FTC CF 3567
11 . modelo da fonte = 0 A639/A441/A397/A597
12 . modelo da fonte = 0 A639/A441/A397/A597
13 . modelo da fonte = 0 A639/A441/A397/A597
Índice da Fonte: 4
4

In [ ]:
grandeza=0
for grandeza in ["0. Ambiente","1. Individual","2. Fluência"]:
  print(grandeza)
grandeza = int(input("Grandeza: "))  
print(grandeza)

0. Ambiente
1. Individual
2. Fluência
Grandeza: 1
1

In [ ]:
#print(table.iloc[fonte,E)
print(table['E'][fonte])

1

In [ ]:
#CÁLCULO DE FLUÊNCIA
d2 = int(input("Distância (em centimetros): "))
t1 = int(input("Tempo(em segundos):  "))
#phi =(table.iloc[fonte,q0]*table.iloc[fonte,A]*table.iloc[fonte,E]*e**(-table.iloc[fonte,Sec_choque]*d2)/(4*pi*d2**2))*(1-e**(-table.iloc[fonte,Lambida_s]*t1))/table.iloc[fonte,Lambida_s]
phi = (table['q0'][fonte]*table['A'][fonte]*table['E'][fonte]*e**(-table['Sec_choque'][fonte]*d2)/(4*pi*d2**2))*(1-e**(-table['Lambida_s'][fonte]*t1))/table['Lambida_s'][fonte]

'''
#Salvando o valor em um local da planilha original
table0['Número série'][20] = "Fluência"
table0['Modelo'][20] = phi
'''
print('A fluência é:', phi, 'n/cm2')

Distância (em centimetros): 200
Tempo(em segundos):  100
A fluência é: 7553.665986100903 n/cm2

In [ ]:
#CÁLCULO Da TAXA DE FLUÊNCIA
d2 = int(input("Distância (em centimetros): "))
phi =table.iloc[fonte,q0]*table.iloc[fonte,A]*table.iloc[fonte,E]*e**(-table.iloc[fonte,Sec_choque]*d2)/(4*pi*d2**2)
print('A taxa de fluência é:', phi, 'n/cm^2/s')

Distância (em centimetros): 100
A taxa de fluência é: 82.45483512541229 n/cm^2/s

In [ ]:
#CÁLCULO DO EQUIVALENTE DE DOSE
d2 = int(input("Distância (em centimetros): "))
t1 = int(input("Tempo(em horas):  "))
if grandeza==0:
  x=14 #ambiente
  y='ambiente'
else:
  x=15 #individual
  y='individual'
H =(3600*(table.iloc[fonte,x]*table.iloc[fonte,q0]*0.000001*table.iloc[fonte,A]*table.iloc[fonte,E]*e**(-table.iloc[fonte,Sec_choque]*d2))/(4*pi*d2**2))*(1-e**(-table.iloc[fonte,Lambida_h]*t1))/table.iloc[fonte,Lambida_h]
print('O equivalente de dose',y,'é:', H, 'uSv')

Distância (em centimetros): 100
Tempo(em horas):  2
O equivalente de dose ambiente é: 47.024523498271634 uSv

In [ ]:
#CÁLCULO DA TAXA DE EQUIVALENTE DE DOSE
d1 = int(input("Distância: "))
if grandeza==0:
  x=14
else:
  x=15
H =(3600*(table.iloc[fonte,x]*table.iloc[fonte,q0]*0.000001*table.iloc[fonte,A]*table.iloc[fonte,E]*e**(-table.iloc[fonte,Sec_choque]*d1))/(4*pi*d1**2))
print('A taxa de equivalente de dose é:', H, 'uSv/h')

Distância: 100
A taxa de equivalente de dose é: 23.512266051436335 uSv/h

In [ ]:
#CÁLCULO DO TEMPO DE IRRADIAÇÃO
d3 = int(input("Distância (em centimetros): "))
flu=0
if grandeza==0:
  x=14
  Eq_amb = int(input("Equivalente de dose ambiente (em uSv):  "))
  t2=-log (1-((Eq_amb*4*pi*d3**2*table.iloc[fonte,Lambida_h])/(3600*table.iloc[fonte,x]*
0.000001*table.iloc[fonte,q0]*table.iloc[fonte,A]*table.iloc[fonte,E]*
e**((-table.iloc[fonte,Sec_choque]*d3)))))/table.iloc[fonte,Lambida_h]
  print ('o tempo de irradiação do equivalente de dose ambiente é:', t2, 'horas')
  
if grandeza==1:
  x=15
  Eq_amb = int(input("Equivalente de dose individual (em uSv):  "))
  t2=-log (1-((Eq_amb*4*pi*d3**2*table.iloc[fonte,Lambida_h])/(3600*table.iloc[fonte,x]*0.000001*table.iloc[fonte,q0]*table.iloc[fonte,A]*table.iloc[fonte,E]*e**((-table.iloc[fonte,Sec_choque]*d3)))))/table.iloc[fonte,Lambida_h]
  print ('o tempo de irradiação do equivalente de dose individual é:', t2, 'horas')

if grandeza==2:
  flu = int(input("Fluência (em n/cm^2):  "))
  t2=-log (1-((flu*4*pi*d3**2*table.iloc[fonte,Lambida_h])/(table.iloc[fonte,q0]*table.iloc[fonte,A]*table.iloc[fonte,E]*e**((-table.iloc[fonte,Sec_choque]*d3)))))/table.iloc[fonte,Lambida_h]
  print ('o tempo de irradiação da fluência é:', t2, 's')

In [ ]:
#Distância Metodo Newton Raphson